### ISSUE TITLE
How do you change the background contrast?

### ISSUE THREAD

**Issue by pective** [f4z3r/gruvbox-material.nvim#20]
I prefer to use the hard contrast, but I have no idea how to change it, and I didnt see anything in the readme about it.

**Comment by f4z3r** [comment]
Hi @pective , thanks for submitting an issue. I am guessing you refer to the hard contrast options from sainnhe's repo? I have not ported these into this version. It is something I would be open to though. I might have a look at this in the coming days maybe.

Which scheme do you use specifically? The material hard? Or one from the mix/original palette? I don't think it would be too much work to port the other palettes either. But I would want to prioritize them, and only add additional palettes if a few people request it.

**Comment by pective** [comment]
Hey, thanks for the quick reply!

I was looking for the material hard option specifically, but i think it would be useful to port the medium and soft versions as well. I would really appreciate it it you ported the material hard contrast option though!

**Comment by f4z3r** [comment]
No worries. I am guessing the medium is pretty close to what we have now already. I will need to validate it though.

I will have a look this week if I get time to port the soft and hard contrasts for the material palette.

I will not port the other palettes (mix and original) yet though.

**Comment by f4z3r** [comment]
I will reopen this as it remains an issue. I would rather keep it open so that the discussion does not get forgotten. I will implement the changes today or tomorrow.

**Comment by pective** [comment]
Alright, thanks for taking your time to implement it!

**Comment by f4z3r** [comment]
Alright, I had some time this morning to get it implemented. You can set the contrast using the configuration now:

```lua
require('gruvbox-material').setup({
  contrast = "medium"         -- set contrast, can be any of "hard", "medium", "soft"
})
```
