### ISSUE TITLE
Spelling Highlight Wrong 

### ISSUE THREAD

**Issue by Parilia** [f4z3r/gruvbox-material.nvim#21]
The spelling highlighting is the sme colour as the text

**Comment by f4z3r** [comment]
I am a bit unsure what you mean by that? Spelling mistakes are underlined. Would you want spelling errors to change the color of the actual text itself? Or do you mean that the undercurl is a different color as the text when launching neovim in the GUI?

**Comment by Parilia** [comment]
The undercurl isnt red for a missspell for instance, It is however the same colour as the text.
