### ISSUE TITLE
[BUG] Inactive buffers in bufferline from barbar.nvim look ugly when using hard contrast

### ISSUE THREAD

**Issue by zenshidev** [f4z3r/gruvbox-material.nvim#37]
### Description

When using hard contract, inactive buffers are coloured purple:
![obraz](https://github.com/user-attachments/assets/33696e83-8063-4987-8a90-7754f90e6601)

This is not an issue on medium contrast:
![obraz](https://github.com/user-attachments/assets/a68ee4c9-d1ba-489b-bf85-1bd456a949e3)

It looks like those buffers use bg4 colour, which for medium contrast looks fine:
![obraz](https://github.com/user-attachments/assets/78518d28-a6e7-4e9a-acdb-213769b5554a)

But for hard contrast does not match rest of the palette at all:
![obraz](https://github.com/user-attachments/assets/0b912e5d-cf10-4316-aa1b-8d8b2be19e8b)

### Screenshot

- [X] I have added a screenshot in the description.

### Expected behavior

Inactive buffers are matching rest of the palette.

### Configuration

```{
  "f4z3r/gruvbox-material.nvim",
  name = "gruvbox-material",
  lazy = false,
  priority = 1000,
  opts = {
    contrast = "hard",
  }
}```

**Comment by f4z3r** [comment]
@zenshixd thanks for reporting this. Yes it seems that I have made a mistake here and taken over the wrong colour. Will fix 👍🏽

**Comment by f4z3r** [comment]
I updated `bg4` and `bg_statusline3` to be the correct colours for the color scheme. Thanks for pointing this out 💯

**Comment by zenshidev** [comment]
Thank you!
