### ISSUE TITLE
Background Transparency

### ISSUE THREAD

**Issue by Parilia** [f4z3r/gruvbox-material.nvim#5]
Backgroundtransparency does not seem to work 

```
vim.g.gruvbox_material_transparent_background = 1
```

Is set and doesnt seem to work

**Comment by f4z3r** [comment]
@Parilia can be you please provide an example screenshot that showcases the issue? Does this issue apply to the background generally, or only to specific parts (such as the sign column)?

**Comment by Parilia** [comment]
Background in general 
![Screenshot_20240401_141257](https://github.com/f4z3r/gruvbox-material.nvim/assets/22579268/5c9693d7-b74a-4af6-b1f9-75b0673c6a48)

**Comment by f4z3r** [comment]
Hi @Parilia , I implemented a small fix for it. I will merge this later today.

Please note that this plugin will not support all the options you have defined above in your config. Feel free to open issues for them if you really want them in this repo.

On a side note: I took over this repo only a few weeks back. I am planning on updating the code a little so that it is easier to add future fixes and potential additions. This will also include a more "lua-oriented" configuration where values are provided directly to the `setup` function instead of globally defined variables.

**Comment by Parilia** [comment]
alright, cool thank you for the fix. if I can I would like to help where I can

**Comment by f4z3r** [comment]
> alright, cool thank you for the fix. if I can I would like to help where I can

Thanks. I will try to setup some issues on the project to track a bit what I think makes sense (and add info to the milestone). If you want to help, feel free to grab something or submit a PR 👍🏽

**Comment by vlanx** [comment]
@f4z3r 
I'm now starting to see this issue again after the code refactor.
<img width="847" alt="Screenshot 2024-05-11 at 18 21 14" src="https://github.com/f4z3r/gruvbox-material.nvim/assets/30477293/e9e17048-cbd6-4655-8706-7fcc251582b0">

My config:
```
return {
  {
    'f4z3r/gruvbox-material.nvim',
    enabled = true,
    lazy = false,
    priority = 1000,
    opts = {
      background = {
        transparent = true, -- set the background to transparent
      },
      float = {
        force_background = true, -- force background on floats even when background.transparent is set
        background_color = nil, -- set color for float backgrounds. If nil, uses the default color set
        -- by the color scheme
      },
    },
  },
}
```

**Comment by Parilia** [comment]
I have no issues with the dark theme

**Comment by f4z3r** [comment]
@dot-1q if you are talking about the floating window having a background, you need to set the `float.force_background` to `false`.

**Comment by vlanx** [comment]
The issue still stands. Changing the transparency (background or float) in the options has no effect on the final transparency value for me.

```
return {
  {
    'f4z3r/gruvbox-material.nvim',
    enabled = true,
    lazy = false,
    priority = 1000,
    opts = {
      background = {
        transparent = true, -- set the background to transparent
      },
      float = {
        force_background = false, -- force background on floats even when background.transparent is set
        background_color = nil, -- set color for float backgrounds. If nil, uses the default color set
        -- by the color scheme
      },
    },
  },
}
```

**Comment by f4z3r** [comment]
Mhhh ok, I will try to have a look at it tomorrow. When you go into the floating window and enter `:Inspect`, what do you get?

**Comment by vlanx** [comment]
I get this:
<img width="848" alt="Screenshot 2024-05-11 at 22 02 52" src="https://github.com/f4z3r/gruvbox-material.nvim/assets/30477293/63ef63c0-e98c-4787-af3e-5373922eb284">
While on this, changing Italics to false doesn't disable italics. I wonder if this is something related to reading the user configs. As you can see, I disabled Italics but in the screenshot they're enabled.
<img width="852" alt="Screenshot 2024-05-11 at 22 03 41" src="https://github.com/f4z3r/gruvbox-material.nvim/assets/30477293/c319d5db-7cb0-4ce1-9e99-7254acaa2ec5">

**Comment by f4z3r** [comment]
Mhhh this is very strange. No matter if I set the background to `light` or `dark` it seems to work for me:

![image](https://github.com/f4z3r/gruvbox-material.nvim/assets/32326425/39fe755b-39c2-4faf-8650-d478c1ccc98b)

with config:

```lua
require("gruvbox-material").setup({
  background = {
    transparent = true,
  },
  float = {
    force_background = true,
  },
})
```

and:

![image](https://github.com/f4z3r/gruvbox-material.nvim/assets/32326425/469390eb-347a-4135-9a92-fd34c8602d2b)

with configuration:

```lua
require("gruvbox-material").setup({
  background = {
    transparent = true,
  },
  float = {
    force_background = false,
  },
})
```

Do you override `NormalFloat` somewhere?

**Comment by vlanx** [comment]
I do not, at least that I'm aware of. But more than that, I'm not able to configure any of the colorscheme options.
I'm using lazynvim, and the plugin file is:
```
return {
  {
    'f4z3r/gruvbox-material.nvim',
    name = 'gruvbox-material',
    lazy = false,
    priority = 1000,
    config = function()
      require('gruvbox-material').setup {
        italics = false, -- enable italics in general
        contrast = 'medium', -- set contrast, can be any of "hard", "medium", "soft"
        comments = {
          italics = false, -- enable italic comments
        },
        background = {
          transparent = true, -- set the background to transparent
        },
        float = {
          force_background = false, -- force background on floats even when background.transparent is set
          background_color = nil, -- set color for float backgrounds. If nil, uses the default color set
          -- by the color scheme
        },
      }
    end,
  },
}
```
I've tried through the `opts = {}` way, and replacing `config` with `init` to no avail.
After [this line](https://github.com/f4z3r/gruvbox-material.nvim/blob/186bfd9fc87ada2e408158bc0f72799b46370add/lua/gruvbox-material/init.lua#L102) I've added:
```
  print(vim.print(cfg))
  print("-----------")
```
And this is the result:
<img width="424" alt="Screenshot 2024-05-12 at 18 40 24" src="https://github.com/f4z3r/gruvbox-material.nvim/assets/30477293/b3b1310b-86ba-4563-a3e2-e3cf54287899">

Seems like its being called more than once and overriding my options. I don't know if this is of any help.

**Comment by f4z3r** [comment]
Puh, seems to be an "issue" with lazy-nvim. I have no experience with it. Maybe @Parilia can help? He uses lazy-nvim as far as I know.

**Comment by Parilia** [comment]
My configs are in my init.lua and are:

```lua
{
    'f4z3r/gruvbox-material.nvim',
    name = 'gruvbox-material',
    lazy = false,
    priority = 1000,
    opts = {
      italics = false,
      comments = { italics = false },
      background = { transparent = true },
      float = {
        force_background = false,
        background_color = nil,
      },
    },
  }
```

Could it perhaps have something to do with your terminal ? If i set my terminal to not be transparent then none of neovim is.

**Comment by f4z3r** [comment]
Ah, I think I know what the problem is. @dot-1q you use auto-dark-mode right? Do you configure it with:

```lua
return {
  "f-person/auto-dark-mode.nvim",
  config = {
    update_interval = 1000,
    set_dark_mode = function()
      vim.api.nvim_set_option("background", "dark")
      vim.cmd("colorscheme gruvbox-material")
    end,
    set_light_mode = function()
      vim.api.nvim_set_option("background", "light")
      vim.cmd("colorscheme gruvbox-material")
    end,
  },
}
```

If you do, every call to `colorscheme gruvbox-material` will call the setup function with default arguments. What you want to do instead is to call `require("gruvbox-material").setup(...)` in the callbacks. So have:

```lua
return {
  "f-person/auto-dark-mode.nvim",
  config = {
    update_interval = 1000,
    set_dark_mode = function()
      vim.api.nvim_set_option("background", "dark")
      require("gruvbox-material").setup({ your opts})
    end,
    set_light_mode = function()
      vim.api.nvim_set_option("background", "light")
      require("gruvbox-material").setup({ your opts})
    end,
  },
}
```

**Comment by vlanx** [comment]
That actually solves my problem yes! Thank you very much!
Although it is strange indeed, since while i was testing i remember disabling that plugin via `enabled=false`, so i'm not sure why loading the color scheme again explicitly solves the issue. 
Thanks for debugging my setup!
